version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "aws-rust-poc-samstackdeploy-prod"
stack_name = "aws-rust-poc-samstack-prod"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "aws-rust-poc"
disable_rollback = true
parameter_overrides = "EnvName=prod"
