AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-rust-poc

  Sample SAM Template for aws-rust-poc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    MemorySize: 128
  Api:
    TracingEnabled: true
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
Mappings:
  EnvironmentVariables:
    databaseUrl:
      dev: AWS::NoValue
      staging: '{{resolve:ssm:alana-auroradb-dev}}'
      prod: '{{resolve:ssm:alana-auroradb-prod}}'
  VpcConfigs:
    SecurityGroupIds:
      dev:
        - AWS::NoValue
      staging:
        - sg-0d47cafade807bc33
      prod:
        - sg-0f0aac8dbce34ab1e
    SubnetIds:
      dev:
        - AWS::NoValue
      staging:
        - subnet-2b511c52
      prod:
        - subnet-99541de0
  CognitoUserPoolsArn:
    recruitersUserPool:
      staging: arn:aws:cognito-idp:us-west-2:524471632441:userpool/us-west-2_U87MvYGL8
      prod: arn:aws:cognito-idp:us-west-2:524471632441:userpool/us-west-2_eFd9n15Jf
Resources:
  AwsRustPocApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvName
      Name: !Sub "AwsRustPocApi-${EnvName}"
      Auth:
        DefaultAuthorizer: RecruiterCognitoAuth # OPTIONAL
        Authorizers:
          RecruiterCognitoAuth:
            UserPoolArn: !FindInMap [ CognitoUserPoolsArn, recruitersUserPool, !Ref EnvName ]
            Identity: # OPTIONAL
              Header: Authorization # OPTIONAL; Default: 'Authorization'
  PingLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/ping/
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures: [ "arm64" ]
      Events:
        Ping:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ping
            Method: get
            RestApiId: !Ref AwsRustPocApi
            Auth:
              Authorizer: NONE
  PingDbLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/ping_db/
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures: [ "arm64" ]
      Events:
        Ping:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ping-db
            Method: get
            RestApiId: !Ref AwsRustPocApi
            Auth:
              Authorizer: RecruiterCognitoAuth
      Environment:
        Variables:
          DATABASE_URL: !FindInMap [ EnvironmentVariables, databaseUrl, !Ref EnvName ]
      VpcConfig:
        SecurityGroupIds: !FindInMap [ VpcConfigs, SecurityGroupIds, !Ref EnvName ]
        SubnetIds: !FindInMap [ VpcConfigs, SubnetIds, !Ref EnvName ]
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
          - ''
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
    Metadata:
      SamResourceId: ApplicationResourceGroup
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
          - ''
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
    Metadata:
      SamResourceId: ApplicationInsightsMonitoring
Outputs:
  PingEndpoint:
    Description: API Gateway endpoint URL for PingLambda
    Value:
      !Join
      - ''
      - - 'https://'
        - !Ref AwsRustPocApi
        - '.execute-api.'
        - !Ref AWS::Region
        - '.amazonaws.com/'
        - !Sub '${AwsRustPocApi.Stage}'
        - '/ping/'
  PingLambdaName:
    Description: Ping Lambda Function Name
    Value:
      !Sub "PingLambda-${EnvName}"
  PingDbEndpoint:
    Description: API Gateway endpoint URL for PingDbLambda
    Value:
      !Join
      - ''
      - - 'https://'
        - !Ref AwsRustPocApi
        - '.execute-api.'
        - !Ref AWS::Region
        - '.amazonaws.com/'
        - !Sub '${AwsRustPocApi.Stage}'
        - '/ping-db/'
  PingDdLambdaName:
    Description: PingDb Lambda Function Name
    Value:
      !Sub "PingDbLambda-${EnvName}"
